### ISSUE TITLE
Don't delete the branch when merge was failed

### ISSUE THREAD

**Issue by nekoya** [nekoya/popuko#17] opened 2016-11-24 05:09 UTC
1. Our project requires status checks
2. trigger `r+` before CI finished
3. Popuko merges PR (fail) and deletes branch

Please keep the branch when occur merging trouble.

**Comment by saneyuki** [comment] 2016-12-02 03:04
This has been fixed by https://github.com/nekoya/popuko/issues/24. By design, it will not delete the branch if merging is failed.

**Closed by saneyuki** 2016-12-02 03:04 UTC
Labels: bug
